name: Build Image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          # Alpine
          - { name: "dev-alpine:latest", path: "Alpine/latest", platforms: "linux/amd64" }
          # Ubuntu
          - { name: "dev-ubuntu:22.04",  path: "Ubuntu/22.04", platforms: "linux/amd64" }
          - { name: "dev-ubuntu:20.04",  path: "Ubuntu/20.04", platforms: "linux/amd64" }
          - { name: "dev-ubuntu:18.04",  path: "Ubuntu/18.04", platforms: "linux/amd64" }
          - { name: "dev-ubuntu:16.04",  path: "Ubuntu/16.04", platforms: "linux/amd64" }

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Build Docker image
        uses: docker/build-push-action@v6.3.0
        with:
          context: ${{ matrix.image.path }}
          push: false
          pull: true
          platforms: ${{ matrix.image.platforms }}
          tags: ams21/${{ matrix.image.name }}
