name: Publish Docker image

on:
  schedule:
    - cron: '0 0 * * *'  # Once a day at midnight.
  push:
    branches:
      - main
    paths:
      # Workflow file itself
      - '.github/workflows/deploy.yml'
      # Dockerfile
      - '**/Dockerfile'
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - { name: "dev-ubuntu:latest", path: "Ubuntu/22.04", platforms: "linux/amd64" }
          # Ubuntu 22.04/Jammy
          - { name: "dev-ubuntu:jammy",  path: "Ubuntu/22.04", platforms: "linux/amd64" }
          - { name: "dev-ubuntu:22.04",  path: "Ubuntu/22.04", platforms: "linux/amd64" }
          # Ubuntu 20.04/Focal
          - { name: "dev-ubuntu:focal",  path: "Ubuntu/20.04", platforms: "linux/amd64" }
          - { name: "dev-ubuntu:20.04",  path: "Ubuntu/20.04", platforms: "linux/amd64" }
          # Ubuntu 18.04/Bionic
          - { name: "dev-ubuntu:bionic", path: "Ubuntu/18.04", platforms: "linux/amd64" }
          - { name: "dev-ubuntu:18.04",  path: "Ubuntu/18.04", platforms: "linux/amd64" }
          # Ubuntu 16.04/Xenial
          - { name: "dev-ubuntu:xenial", path: "Ubuntu/16.04", platforms: "linux/amd64" }
          - { name: "dev-ubuntu:16.04",  path: "Ubuntu/16.04", platforms: "linux/amd64" }

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: ${{ matrix.image.path }}
          push: true
          pull: true
          platforms: ${{ matrix.image.platforms }}
          tags: |
            ams21/${{ matrix.image.name }}
            ghcr.io/ams21/${{ matrix.image.name }}
